# Generated by Django 5.1.1 on 2024-10-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
    ]
