# Generated by Django 5.1.1 on 2024-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_alter_article_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECU'), ('R', 'PROFORMA FACTURE'), ('F', 'FACTURE')], max_length=1),
        ),
    ]
